language: ruby
    
before_install:
  - gem install bundler

rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - rbx-19mode

gemfile:
  - Gemfile

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    - ci-admins@identified.com
